name: Correcting Hangman

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2.3.1
      
      - name: Download the marking package
        run: |
          python -m pip install --upgrade pip
          pip install hangman-marking-aicore

      - name: Verify milestone 1 tasks
        run: |
          python -m unittest -v hangman_test.test_milestone1 2> milestone_1.txt
      
      - name: Tick off boxes in milestone 1
        run: |
          python -m hangman_test.verify_milestone1
        if: always()
        env:
          USER_ID: ${{ secrets.USER_ID }}
          API_TOKEN: ${{ secrets.API_TOKEN }}
